name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels
          plugin_achievements: true
          plugin_activity: true
          plugin_activity_visibility: public
          plugin_followup: true
          plugin_followup_sections: repositories, user
          plugin_gists: true
          plugin_habits: true
          plugin_introduction: true
          plugin_isocalendar: true
          plugin_languages: true
          plugin_languages_threshold: 1
          plugin_languages_other: true
          plugin_notable: true
          plugin_stars: true
          plugin_topics: true
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
