name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: read
      packages: read
      checks: read
      issues: read
      statuses: read
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets..GITHUB_TOKEN }}
          config_timezone: Europe/Brussels
          plugin_achievements: true
          plugin_achievements_threshold: A
          plugin_achievements_limit: 10
          plugin_activity: false
          plugin_activity_visibility: public
          plugin_followup: false
          plugin_gists: false
          plugin_habits: true
          plugin_introduction: true
          plugin_isocalendar: true
          plugin_languages: false
          plugin_notable: true
          plugin_stars: false
          plugin_topics: false
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
